### ISSUE TITLE
Clear password on F5 Host does not work.

### ISSUE THREAD

**Issue by jeremy-church1** [f5devcentral/vscode-f5#179] opened 2022-04-27 21:11 UTC
When I right-click on a host and choose "clear password", next time I click on the host, it will not prompt for a password and will continue to connect with the incorrect password. Usually locking my account for a period of time.

What I've tried that hasn't worked:
Clear password, deleting the devices. Then adding them back.
Clear password, deleting the devices, then adding them back via JSON containing the correct password in a password field.

Usually it takes some combination of clearing the password, deleting the devices, then closing and re-opening VS Code.

A "set password" option that immediately prompts for, and then writes the password to cache should work around this issue as well.

Thanks

**Comment by DumpySquare** [comment] 2022-04-28 20:29
Thanks for opening this.  I will be looking into this soon.

I have implemented a "clear all passwords" command, but also need to rework some of the logic when connecting and detecting a failed password.

**Comment by Gururajnrao** [comment] 2022-05-25 13:57
I see similar issue in the below version

Vscode version: 1.67.1 and F5 extension version: v3.7.1

**Comment by walterk82** [comment] 2022-06-03 15:42
This bug is causing my account to get locked in BIG-IP due to excessive retries with a bad password.  VS.Code reports this error message:
`Error running command f5.clearPassword: Unexpected token G in JSON at position 0. This is likely caused by the extension that contributes f5.clearPassword.`

**Comment by DumpySquare** [comment] 2022-06-24 17:08
Thanks everyone.  I will be releasing a fix for this next month.  Sorry for the delay.

**Comment by DumpySquare** [comment] 2022-09-02 16:02
Hi everyone,   This should be resolved with some of the recent releases.  Can you please confirm?

**Comment by DumpySquare** [comment] 2022-12-08 20:13
Hey everyone.  Is this issue resolved?  I will be closing this issue soon.

**Comment by DumpySquare** [comment] 2023-03-01 15:32
resolved

**Closed by DumpySquare** 2023-03-01 15:32 UTC
Labels: bug
