### ISSUE TITLE
Unable to add BIG-IP after upgrade to VSCode 1.83

### ISSUE THREAD

**Issue by jgoldsworth-f5** [f5devcentral/vscode-f5#230] opened 2023-10-10 17:58 UTC
![Screenshot 2023-10-10 at 1 55 03 PM](https://github.com/f5devcentral/vscode-f5/assets/101671820/89e09751-a023-46ec-89cf-8c0e2e197a69)
After an ugrade to VSCode 1.83, I am no longer able to view or access any of my existing devices.  Upon attempting to add a new device I'm getting the following error:

"Error running command f5.addHost: command 'f5.addHost' not found. This is likely caused by the extension that contributes f5.addHost."

I've attempted installing an older version of the extension with no luck.  This issue occurs on both Windows and Mac OS.  This is also occuring for other people as well that I am working with.

**Comment by krisdames** [comment] 2023-10-11 17:37
Same here. I opened VSCode 1.83 today and all of my F5 Hosts were gone. I get the same message as @jgoldsworth-f5 when I try to create a new one. I uninstalled and reinstall the F5 extension but it did not help. The runtime status of my F5 Extension is "Not yet activated."

I am running Windows 10 Enterprise Version 10.0.19044 Build 19044.

VSCode info:
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by DahlPatric** [comment] 2023-10-11 19:44
Same error for as for previews posts.
A solution would be very much appreciated.

**Comment by jmcalalang** [comment] 2023-10-12 15:15
dub of #229

**Comment by DumpySquare** [comment] 2023-10-16 12:17
Thanks for opening this issue.  Looking into this.  For now, people seem to have success with rolling vscode back to 1.82

**Comment by danielcayer** [comment] 2023-10-17 13:25
Downgrading VSCode to v1.82 resolved this issue for me (and also fixed issues I was having with Docker extension).

**Comment by cwoods71** [comment] 2023-10-19 00:48
confirmed as well under both stable and preview apps, going to roll stable back to 1.82. Also of note, after installing the extension, I right click on an unencrypted UCS file and it never loads in F5 config explorer. Been using this for years and first time I've run into this. Status of the extensions under both apps is not activated.

**Comment by DumpySquare** [comment] 2023-10-26 17:06
Just released 3.15. that should fix this.  Please confirm

**Comment by krisdames** [comment] 2023-10-30 18:23
Works for me now, confirmed that this fixed my issue. Thank you!

**Comment by DumpySquare** [comment] 2023-11-07 16:12
fix confirmed.  closing

**Closed by DumpySquare** 2023-11-07 16:12 UTC
